### ISSUE TITLE
Release 2 CAD missing idler_arm_long

### ISSUE THREAD

**Issue by 310weber** [Annex-Engineering/Sherpa_Mini-Extruder#40]
The CAD for release 2 seems to be missing the idler_arm_long part (or rather the part shows up in the model tree but is empty).

Steps to reproduce:
1. download parasolid model [sherpa_mini_release_2.x_t](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/blob/master/CAD/sherpa_mini_release_2.x_t) from commit [fa76f44](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/commit/fa76f449e86c1e4ee2c25fc557be01597a096812)
2. import model to Onshape
3. navigate to "idler_arm_long^housing_sherpa_mini_a3_r16(FDM)" in the model tree
4. part is empty

![image](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/assets/2540542/0c78d618-1d4e-4b28-b3cc-7a31fe91e6d1)

**Comment by ChaosBlades** [comment]
It is not missing... just really really small 🤣 I compared Release 1 and Release 2 arms. The geometry is different so you can't simply split the old thumb lever and add it to the new idler arm short.
![Screenshot from 2024-02-28 03-28-06](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/assets/7530545/c3a6b1d3-1e6c-480e-80bb-55be9c6dc311)
Also, would be nice when this is fixed it is updated to a Step file instead of the Parasolid file. The ONLY free way a user can use that file is add it to Onshape then export it as a Step. Who knows how long it will be before that is locked behind a pay wall as well.

So people don't have to make an Onshape account to use the current CAD I have already converted it.
[sherpa_mini_release_2.zip](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/files/14431012/sherpa_mini_release_2.zip)
FYI: It will import with the distance being measured in meters instead of millimeters.

**Comment by anlin93** [comment]
This looks to be an issue related to Onshape. The X_T opens fine in SolidWorks, long idler arm included. As it has been a frequent request, STEP files will be provided with next release
![idler_arm](https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/assets/7979999/1280984a-24df-4c19-8b34-0dd6f051b6f5)
